import colors from './colors';

export const animations = {
  windmill: {
    source: require('../assets/lottie-animations/windmill-animation.json'),
    height: 412,
    colors: {
      appNameColor: colors.green500,
      backgroundColor: '#F6EAEF',
      greetingTextColor: '#7a9568',
      emojiContainerBackgroundColor: '#ccddc1',
      emojiColor: '#6a825b',
      emojiBackgroundColor: '#f5f8f3',
      underTextColor: '#4c5d41',
      buttonColor: '#98BA82',
      buttonTextColor: 'white',
      logoutTextColor: '#5b704e',
    },
  },
  beach: {
    source: require('../assets/lottie-animations/beach-animation.json'),
    height: 400,
    colors: {
      appNameColor: colors.blue500,
      backgroundColor: '#a6dcf1',
      greetingTextColor: '#167599',
      emojiContainerBackgroundColor: '#90d3ed',
      emojiColor: '#1d96c5',
      emojiBackgroundColor: colors.blue100,
      underTextColor: '#36b0df',
      buttonColor: '#20a7db',
      buttonTextColor: 'white',
      logoutTextColor: colors.blue100,
    },
  },
  autumn: {
    source: require('../assets/lottie-animations/autumn-animation.json'),
    height: 300,
    colors: {
      appNameColor: colors.orange500,
      backgroundColor: '#ffecde',
      greetingTextColor: '#7a9568',
      emojiContainerBackgroundColor: '#ffd0ae',
      emojiColor: '#80512e',
      emojiBackgroundColor: '#f5f8f3',
      underTextColor: '#80512e',
      buttonColor: '#98BA82',
      buttonTextColor: 'white',
      logoutTextColor: '#e69153',
    },
  },
  chill: {
    source: require('../assets/lottie-animations/chill-animation.json'),
    height: 320,
    colors: {
      appNameColor: colors.green500,
      backgroundColor: '#faffec',
      greetingTextColor: '#7a9568',
      emojiContainerBackgroundColor: '#efffbe',
      emojiColor: '#6a825b',
      emojiBackgroundColor: 'white',
      underTextColor: '#4c5d41',
      buttonColor: '#98BA82',
      buttonTextColor: 'white',
      logoutTextColor: '#bfcc98',
    },
  },
  meditating: {
    source: require('../assets/lottie-animations/meditating-animation.json'),
    height: 412,
    colors: {
      appNameColor: colors.blue500,
      backgroundColor: colors.blue300,
      greetingTextColor: colors.blue700,
      emojiContainerBackgroundColor: colors.blue400a50,
      emojiColor: colors.blue600,
      emojiBackgroundColor: colors.blue100,
      underTextColor: colors.blue600,
      buttonColor: colors.blue600,
      buttonTextColor: 'white',
      logoutTextColor: colors.blue200,
    },
  },
};
